name: Issue作成者への自動アサイン

on:
  issues:
    types: [opened]
jobs:
  auto-assign-author:
    # バージョン自動更新の際は除外
    if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1